option(SOLUNA_BUILD_TESTS "Build unit tests" ON)
option(SOLUNA_BUILD_BENCHMARKS "Build benchmarks" OFF)
option(SOLUNA_BUILD_STRESS_TESTS "Build stress tests" OFF)
option(SOLUNA_ENABLE_OPUS "Enable Opus codec for WiFi" ON)
option(SOLUNA_ENABLE_AAC "Enable AAC codec (requires FDK-AAC)" OFF)
option(SOLUNA_ENABLE_FLAC "Enable FLAC codec (requires libFLAC)" OFF)
option(SOLUNA_ENABLE_AES67 "Enable AES67 compatibility mode" ON)
option(SOLUNA_ENABLE_RAVENNA "Enable Ravenna compatibility (requires AES67)" OFF)
option(SOLUNA_ENABLE_DLNA "Enable DLNA/UPnP Media Renderer" OFF)
option(SOLUNA_ENABLE_AIRPLAY "Enable AirPlay 2 receiver + sender (TX)" OFF)
option(SOLUNA_ENABLE_DTLS "Enable DTLS encryption (requires OpenSSL)" OFF)
option(SOLUNA_ENABLE_TLS "Enable HTTPS/WSS for WebSocket server (requires OpenSSL)" OFF)
option(SOLUNA_BUILD_VST "Build VST3 audio plugin" OFF)
option(SOLUNA_ESP32 "Build for ESP32 target" OFF)
option(SOLUNA_ENABLE_PIPEWIRE "Enable PipeWire audio output (Linux only)" OFF)
